# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://15.165.73.36:3306/metalog

    # mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: metalog
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  file:
    upload-dir: "C:\\Users\\phr80\\OneDrive\\사진\\스크린샷"
